"""add unique constraint to name column in tags table

Revision ID: ad08eaaee1f2
Revises: 759d2664aa05
Create Date: 2022-07-27 15:21:14.865602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad08eaaee1f2'
down_revision = '759d2664aa05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    # ### end Alembic commands ###
