"""empty message

Revision ID: 05bc9889da43
Revises: e030002cfb93
Create Date: 2022-07-25 17:35:00.436996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bc9889da43'
down_revision = 'e030002cfb93'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('comments') as batch_op:
        batch_op.alter_column(column_name='content',
                    existing_type=sa.VARCHAR(),
                    new_column_name='content',
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments') as batch_op:
        batch_op.alter_column(column_name='content',
                    existing_type=sa.VARCHAR(),
                    new_column_name='content',
                    nullable=False)
    # ### end Alembic commands ###
