"""empty message

Revision ID: 05bc9889da43
Revises: e030002cfb93
Create Date: 2022-07-25 17:35:00.436996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bc9889da43'
down_revision = 'e030002cfb93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.VARCHAR(length=2200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.VARCHAR(length=2200),
               nullable=True)
    # ### end Alembic commands ###
